spring:
  application:
    name: demo

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

otel:
  service:
    name: producer-service
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}